export enum PLATFORM {
  PDD = 1, // (1, "pdd", "拼多多"),
  YOUZAN = 2, // (2, "youzan", "有赞"),
  ALBB = 3, //(3, "1688", "阿里巴巴"),
  JD = 4, //(4, "jd", "京东"),
  YJ = 5, //(5, "yj", "云集"),
  WD = 6, //(6, "wd", "微店"),
  WXXD = 7, //XD(7, "wxxd", "微信小店"),
  TB = 8, //(8, "tb", "淘宝"),
  TM = 9, //(9, "tm", "天猫"),
  DD = 10, //(10, "dd", "当当"),
  PP = 11, //(11, "pp", "拍拍"),
  YX = 12, //(12, "yx", "易讯"),
  EBAY = 13, // EBAY(13, "ebay", "EBAY"),
  QQ = 14, // QQ(14, "qq", "QQ网购"),
  AMAZON = 15, // AMAZON(15, "amazon", "亚马逊"),
  SN = 16, // SN(16, "sn", "苏宁"),
  GM = 17, // GM(17, "gm", "国美"),
  WPH = 18, // WPH(18, "wph", "唯品会"),
  JM = 19, // JM(19, "jm", "聚美优品"),
  LF = 20, // LF(20, "lf", "乐蜂"),
  MGJ = 21, // MGJ(21, "mgj", "蘑菇街"),
  JS = 22, // JS(22, "js", "聚尚"),
  PX = 23, // PX(23, "px", "拍鞋"),
  YT = 24, // YT(24, "yt", "银泰"),
  YHD = 25, // YHD(25, "yhd", "1号店"),
  VANCL = 26, // VANCL(26, "vancl", "凡客"),
  YL = 27, // YL(27, "yl", "邮乐"),
  YG = 28, // YG(28, "yg", "优购"),
  WDH5 = 29, // WDH5(29, "wdh5", "微店H5"),
  XYT = 30, // XYT(30, "xyt", "小亚通"),
  YOUZANYUN = 31, // YOUZANYUN(31, "youzanyun", "有赞云"),
  FHDANT = 32, // FHDANT(32, "fhdant", "风火蚁"),
  KS = 33, //(33, "ks", "快手"),
  FXG = 34, // FXG(34, "fxg", "放心购"),//头条系 抖音、值点、鲁班、火山小店
  KTT = 35, // KTT(35, "ktt", "快团团"),//拼多多的新平台
  C2M = 36, // C2M(36, "c2m", "淘工厂"),//阿里巴巴新平台
  WXXSD = 37, // WXXSD(37, "wxxsd", "微信小商店"),//原微信小店
  ZCY = 38, // ZCY(38, "zcy", "政采云"),
  FTH = 39, // FTH(39, "fth", "风天河"),
  FHD = 99, // FHD(99, "fhd", "风火递"),
  FHK = 100, // FHK(100, "fhk", "库小存"),
  ANT = 101, // ANT(101, "ant", "商家版风火蚁"),
  WMS = 102, // WMS(102, "wms", "WMS平台推送"),
  FOO = 103 // FOO(103, "foo", "开放平台自有商城");
}

export enum ShopOperationType {
  FIRST_LOGIN = 1, //("FIRST_LOGIN", 1), // 新用户数
  SYNC_COMP = 2, //("SYNC_COMP", 2), // 完成同步用户
  SYNC_COMP_ADV = 3, //("SYNC_COMP_ADV", 3), // 付费完成同步用户
  PRINT_COMP = 4, //("PRINT_COMP", 4), // 完成打印用户
  PRINT_COMP_ADV = 5, //("PRINT_COMP_ADV", 5), // 付费完成打印用户
  SEND_COMP = 6, //("SEND_COMP", 6), // 完成发货用户
  SEND_COMP_ADV = 7, //("SEND_COMP_ADV", 7), // 付费完成发货用户
  SEVEN_TRY = 8, //("SEVEN_TRY", 8), // 7天试用用户
  ZERO_TRY = 9, //("ZERO_TRY", 9), // 0元试用用户
  NEW_PAY = 10, //("NEW_PAY", 10), // 新付费用户
  EXPIRE_TIME = 11 //("EXPIRE_TIME", 11);// 到期时间
}
